modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="uchip"
version="${file.jarVersion}"
displayName="Microchips"
logoFile="uchip.png"
authors="ALotOfLetters"
description='''
Create computers with microchips.
'''

[[dependencies.uchip]]
    modId="forge" 
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.uchip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.3)"
    ordering="NONE"
    side="BOTH"
